### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Silent-Hunter** [GyozaGuy/Skype-Electron#5]
Thanks for the help! However build.sh now fails with this:

silent@TERMINAL-BMRF-9 ~/Skype-Electron $ ./build.sh
/usr/lib64/node_modules/electron-packager/common.js:67
  return `${opts.name}-${opts.platform}-${opts.arch}`
         ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib64/node_modules/electron-packager/cli.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by GyozaGuy** [comment]
Interesting, I haven't seen that before. I was able to find this though: [https://github.com/electron-userland/electron-packager/issues/348](https://github.com/electron-userland/electron-packager/issues/348)

Is your version of Node up to date?

**Comment by Silent-Hunter** [comment]
Ah no, it wasn't. I was able to force Portage to install a newer one and it
works now. Thanks!

**Comment by GyozaGuy** [comment]
No problem! Glad you got it working.
