### ISSUE TITLE
Skype-Electron fails to launch with Electron 1.0.1

### ISSUE THREAD

**Issue by gourdcaptain** [GyozaGuy/Skype-Electron#6]
Using Skype-Electron on Arch Linux with Electron from the AUR. When it upgraded to 1.0.1, Skype-Electron fails to launch with the error:
App threw an error when running [Error: companyName is a required option to crashReporter.start]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: companyName is a required option to crashReporter.start
    at CrashReporter.start (/usr/share/electron/resources/electron.asar/common/api/crash-reporter.js:47:13)
    at Object.<anonymous> (/usr/share/skype-electron/main.js:20:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at loadApplicationPackage (/usr/share/electron/resources/default_app.asar/main.js:253:23)
    at Object.<anonymous> (/usr/share/electron/resources/default_app.asar/main.js:293:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
Commenting out the line "electron.crashReporter.start();" in Skype-Electron's main.js file was a quick workaround for this issue I used.

**Comment by GyozaGuy** [comment]
I noticed this just today as well, it looks like the new version changed stuff in the crashReporter, probably that part about `Error: companyName is a required option to crashReporter.start`. I'll look into changing that or just removing it since I don't really even utilize it anyway.

**Comment by GyozaGuy** [comment]
This is fixed now, I just removed the `crashReporter` line since I wasn't really using it.
